import { format, startOfWeek, endOfWeek } from 'date-fns';
import type { CalendarSession } from './api';
import type { TrainingLoad } from '@/types';

export interface WeeklySummaryData {
  weekStart: string;
  weekEnd: string;
  plannedSessions: number;
  completedSessions: number;
  totalLoad: number;
  insight: string;
  trainingLoad?: TrainingLoad[];
}

/**
 * Generates a shareable text summary of the week
 */
export function generateWeeklySummaryText(data: WeeklySummaryData): string {
  const weekRange = `${format(new Date(data.weekStart), 'MMM d')} - ${format(new Date(data.weekEnd), 'MMM d, yyyy')}`;
  
  const lines: string[] = [];
  lines.push(`📅 Weekly Training Summary - ${weekRange}`);
  lines.push('');
  lines.push(`✅ Completed: ${data.completedSessions} / ${data.plannedSessions} sessions`);
  lines.push(`📊 Total Load: ${data.totalLoad} TSS`);
  lines.push('');
  
  if (data.insight) {
    lines.push(`💡 Weekly Insight:`);
    lines.push(data.insight);
    lines.push('');
  }
  
  if (data.trainingLoad && data.trainingLoad.length > 0) {
    const latest = data.trainingLoad[data.trainingLoad.length - 1];
    lines.push(`📈 Training Metrics:`);
    lines.push(`   Fitness (CTL): ${latest.ctl.toFixed(0)}`);
    lines.push(`   Fatigue (ATL): ${latest.atl.toFixed(0)}`);
    lines.push(`   Form (TSB): ${latest.tsb > 0 ? '+' : ''}${latest.tsb.toFixed(0)}`);
    lines.push('');
  }
  
  lines.push('Generated by AthleteSpace');
  
  return lines.join('\n');
}

/**
 * Generates a shareable markdown summary
 */
export function generateWeeklySummaryMarkdown(data: WeeklySummaryData): string {
  const weekRange = `${format(new Date(data.weekStart), 'MMM d')} - ${format(new Date(data.weekEnd), 'MMM d, yyyy')}`;
  
  const lines: string[] = [];
  lines.push(`# Weekly Training Summary`);
  lines.push(`**${weekRange}**`);
  lines.push('');
  lines.push(`## Overview`);
  lines.push(`- ✅ Completed: **${data.completedSessions}** / ${data.plannedSessions} sessions`);
  lines.push(`- 📊 Total Load: **${data.totalLoad} TSS**`);
  lines.push('');
  
  if (data.insight) {
    lines.push(`## 💡 Weekly Insight`);
    lines.push(data.insight);
    lines.push('');
  }
  
  if (data.trainingLoad && data.trainingLoad.length > 0) {
    const latest = data.trainingLoad[data.trainingLoad.length - 1];
    lines.push(`## 📈 Training Metrics`);
    lines.push(`- **Fitness (CTL):** ${latest.ctl.toFixed(0)}`);
    lines.push(`- **Fatigue (ATL):** ${latest.atl.toFixed(0)}`);
    lines.push(`- **Form (TSB):** ${latest.tsb > 0 ? '+' : ''}${latest.tsb.toFixed(0)}`);
    lines.push('');
  }
  
  lines.push('---');
  lines.push('*Generated by AthleteSpace*');
  
  return lines.join('\n');
}

/**
 * Copies text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Downloads text as a file
 */
export function downloadTextFile(content: string, filename: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Shares content using Web Share API if available
 */
export async function shareContent(title: string, text: string, url?: string): Promise<boolean> {
  if (!navigator.share) {
    return false;
  }
  
  try {
    await navigator.share({
      title,
      text,
      url: url || window.location.href,
    });
    return true;
  } catch (error) {
    // User cancelled or error occurred
    if ((error as Error).name !== 'AbortError') {
      console.error('Failed to share:', error);
    }
    return false;
  }
}

