import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Brain } from 'lucide-react';

interface CoachInsightCardProps {
  coachInsight: string;
  className?: string;
}

export function CoachInsightCard({ coachInsight, className }: CoachInsightCardProps) {
  if (!coachInsight) {
    return null;
  }

  return (
    <Card className={className}>
      <CardHeader className="pb-3">
        <div className="flex items-center gap-2">
          <Brain className="h-5 w-5 text-primary" />
          <CardTitle className="text-lg">Coach Insight</CardTitle>
        </div>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">
          {coachInsight}
        </p>
        <div className="mt-4 pt-4 border-t border-border">
          <p className="text-xs text-muted-foreground italic">
            Generated by your AI coach using your recent training and recovery context
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
